apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: users-api
          image: orennu/kub-deploy-tasks-challenge:latest
          resources:
            limits:
              cpu: "0.25"
              memory: 256Mi
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://orenn:wEC2wZh5m97NUJR@kub-eks-demo0.vffiamv.mongodb.net/tasks?retryWrites=true&w=majority"
            - name: AUTH_API_ADDRESS
              value: "auth-service.default:3000"
