apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-second-app-pod
      tier: backend
    # matchExpressions:
    #   - {
    #       key: app,
    #       operator: In,
    #       values: [node-second-app-pod, node-first-app-pod],
    #     }
  template:
    metadata:
      labels:
        app: node-second-app-pod
        tier: backend
    spec:
      containers:
        - name: node-second-app
          image: orennu/kub-declarative-app:0.0.6
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
