apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: orennu/kub-net-auth-demo:latest
          resources:
            limits:
              cpu: "0.25"
              memory: 256Mi
